name: build and push to docker hub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run:
          mvn clean package --file pom.xml
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ashwinraj18/mte-api:1.0
      - name: Docker Push
        run: docker push ashwinraj18/mte-api:1.0
      - name: Deploy on AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_TWEAK_HOST }}
          username: ${{ secrets.AWS_TWEAK_USERNAME }}
          key: ${{ secrets.AWS_TWEAK_KEY }}
          port: 22
          script: |
            sudo docker rm -f mte-app
            sudo docker rmi ashwinraj18/mte-api:1.0
            sudo docker pull ashwinraj18/mte-api:1.0
            sudo docker run -d -p 8095:8080 --name mte-app --network mte-network -e REDIS_URL='redisjson-mte:6379' -e SQ_URL=${{secrets.SQ_URL}} -e SQ_TOKEN=${{secrets.SQ_TOKEN}} -e JIRA_URL=${{secrets.JIRA_URL}} -e JIRA_USERNAME=${{secrets.JIRA_USERNAME}} -e JIRA_TOKEN=${{secrets.JIRA_TOKEN}} -e BD_URL=${{secrets.BD_URL}} -e BD_TOKEN=${{secrets.BD_TOKEN}} ashwinraj18/mte-api:1.0
            exit